### ISSUE TITLE
Provide syntax highlighting for JavaScript in the JSNI methods

### ISSUE THREAD

**Issue by ksfreitas** [ksfreitas/gwt4nb#2] opened 2012-09-01 15:50 UTC
See 
http://code.google.com/webtoolkit/documentation/com.google.gwt.doc.DeveloperGuide.JavaScriptNativeI
nterface.JavaScriptFromJava.html

Imported from http://java.net/jira/browse/GWT4NB-5

**Comment by markiewb** [comment] 2016-03-07 20:30
Duplicate of #36

**Closed by markiewb** 2016-03-07 20:30 UTC
Labels: duplicate, enhancement
